### ISSUE TITLE
based_aa: Remove `antialiaser` param

### ISSUE THREAD

**Issue by LightArrowsEXE** [Jaded-Encoding-Thaumaturgy/vs-aa#27]
Currently, we accept an `antialiser` parameter for `based_aa`. However, this parameter is kinda pointless.
The core functionality of the function depends on `sclip`, which is something only Eedi3 has. While you may be able to hack together something for other AAs, no attempt to do so is currently implemented.

The following should be changed:

- The `antialiaser` parameter should be removed
- The kwargs should be passed onto an Eedi3 class instead

The drawback to doing this is that users (myself included) use the `antialiaser` parameter to tweak Eedi3 settings in their scripts. That's why I also propose we add a deprecation warning for the `antialiaser` parameter. We can still use it as-is, plus check for any kwargs passed for the time being, and ultimately get rid of it in the next version.

This is a rather big change and I'm not exactly sure how you would want this implemented, so I'm leaving it as an issue for the time being @Setsugennoao.

**Comment by Setsugennoao** [comment]
what's the point of any of this? you can already pass kwargs and edit eedi3 parameters
you're just removing functionality

**Comment by LightArrowsEXE** [comment]
Functionality that is broken, unsupported, and if we wanted to support, we would have to write specific code for every AA function we want to support.
